# Configurations of Pets Store app.

# Default theme for this app.
theme : "org.wso2.carbon.uuf.common.default.theme"

# Menus in this app.
menus :
  - name: "main"
    items:
      - text: "Home"
        link: "#"
        icon: "fw-home"
      - text: "Pets"
        link: ""
        submenus:
          - text: "See all our amazing pets"
            link: "/pets"
          - text: "Add a new pet"
            link: "/pets/new"
            icon: "fw fw-add"
          - text: "Pet of the month"
            link: "/pets/snowball"
          - text: "Order new pets"
            link: "/pets/order"

# Error pages for this app.
errorPages:
  404: "/foundation/error/404"
  default: "/foundation/error/default"

# URI of the login page in this app.
loginPageUri: "/simple-auth/login"

# Security related configurations for this app.
security:
  csrfIgnoreUris:
    - /simple-auth/login
    - /simple-auth/register
  xssIgnoreUris: []
  responseHeaders:
     staticResources:
      "Content-Security-Policy": "default-src 'none'; script-src 'self' ssl.google-analytics.com;"
     pages:
      "X-Frame-Options": "DENY"

