# Configurations of Pets Store app.

# Default theme for this app.
theme : "org.wso2.carbon.uuf.sample.default.theme"

# Session manager configuration for this app
sessionManagement:
  factoryClassName: "org.wso2.carbon.uuf.sample.simpleauth.bundle.api.auth.PersistentSessionManagerFactory"
  timeout: 600

# Menus in this app.
menus :
  - name: "main"
    items:
      - text: "menu.main.home"
        link: "#"
        icon: "fw-home"
      - text: "menu.main.pets"
        link: ""
        submenus:
          - text: "menu.main.see-all"
            link: "/pets"
          - text: "menu.main.add-new"
            link: "/pets/new"
            icon: "fw fw-add"
          - text: "menu.main.month-pet"
            link: "/pets/snowball"
          - text: "menu.main.order-new"
            link: "/pets/order"

# Error pages for this app.
errorPages:
  404: "/foundation/error/404"
  default: "/foundation/error/default"

# URI of the login page in this app.
loginPageUri: "/simple-auth/login"

# Security related configurations for this app.
security:
  csrfIgnoreUris:
    - /simple-auth/login
    - /simple-auth/register
  xssIgnoreUris: []
  responseHeaders:
    staticResources:
      "Content-Security-Policy": "default-src 'none'; script-src 'self' ssl.google-analytics.com;"
    pages:
      "X-Frame-Options": "DENY"
