/**
 * Application constants.
 * @type {{DIRECTORY_APP: string, DIRECTORY_APP_LAYOUTS: string, DIRECTORY_APP_PAGES: string,
 *     DIRECTORY_APP_UNITS: string, DIRECTORY_APP_UNIT_PUBLIC: string, DIRECTORY_CACHE: string,
 *     DIRECTORY_CONF: string, DIRECTORY_LIB: string, DIRECTORY_MODULES: string, FILE_APP_CONF:
 *     string, FILE_UUF_CONF: string, MODULE_AUTH: string, MODULE_HANDLEBARS: string, MODULE_LESS:
 *     string, APP_CONF_APP_NAME: string, APP_CONF_CACHE_ENABLED: string,
 *     APP_CONF_DEBUGGING_ENABLED: string, APP_CONF_PERMISSION_ROOT: string,
 *     APP_CONF_ADMIN_SERVICES_URL: string, APP_CONF_LOGIN_PAGE: string, APP_CONF_ERROR_PAGES:
 *     string, APP_CONF_AUTH_MODULE: string, APP_CONF_AUTH_MODULE_ENABLED: string,
 *     APP_CONF_AUTH_MODULE_TRANSPORT: string, APP_CONF_AUTH_MODULE_LOGIN: string,
 *     APP_CONF_AUTH_MODULE_LOGIN_ON_SUCCESS: string, APP_CONF_AUTH_MODULE_LOGIN_ON_SUCCESS_SCRIPT:
 *     string, APP_CONF_AUTH_MODULE_LOGIN_ON_SUCCESS_PAGE: string,
 *     APP_CONF_AUTH_MODULE_LOGIN_ON_FAIL: string, APP_CONF_AUTH_MODULE_LOGIN_ON_FAIL_SCRIPT:
 *     string, APP_CONF_AUTH_MODULE_LOGIN_ON_FAIL_PAGE: string, APP_CONF_AUTH_MODULE_LOGOUT:
 *     string, APP_CONF_AUTH_MODULE_LOGOUT_ON_SUCCESS: string,
 *     APP_CONF_AUTH_MODULE_LOGOUT_ON_SUCCESS_SCRIPT: string,
 *     APP_CONF_AUTH_MODULE_LOGOUT_ON_SUCCESS_PAGE: string, APP_CONF_AUTH_MODULE_LOGOUT_ON_FAIL:
 *     string, APP_CONF_AUTH_MODULE_LOGOUT_ON_FAIL_SCRIPT: string,
 *     APP_CONF_AUTH_MODULE_LOGOUT_ON_FAIL_PAGE: string, APP_CONF_AUTH_MODULE_SSO: string,
 *     APP_CONF_AUTH_MODULE_SSO_ENABLED: string, APP_CONF_AUTH_MODULE_SSO_ISSUER: string,
 *     APP_CONF_AUTH_MODULE_SSO_RESPONSE_SIGNING_ENABLED: string,
 *     APP_CONF_AUTH_MODULE_SSO_KEY_STORE_NAME: string,
 *     APP_CONF_AUTH_MODULE_SSO_KEY_STORE_PASSWORD: string,
 *     APP_CONF_AUTH_MODULE_SSO_IDENTITY_PROVIDER_ALIAS: string,
 *     APP_CONF_AUTH_MODULE_SSO_IDENTITY_PROVIDER_URL: string,
 *     APP_CONF_AUTH_MODULE_SSO_INTERMEDIATE_PAGE: string, UUF_CONF_DISPLAY_NAME: string,
 *     UUF_CONF_LOG_LEVEL: string, UUF_CONF_ERROR_PAGES: string, UUF_CONF_SECURITY_CONSTRAINTS:
 *     string, UI_COMPONENT_JS_FUNCTION_ON_REQUEST: string, UI_COMPONENT_DEFINITION_VERSION:
 *     string, UI_COMPONENT_DEFINITION_INDEX: string, UI_COMPONENT_DEFINITION_EXTENDS: string,
 *     UI_COMPONENT_DEFINITION_PERMISSIONS: string, UI_COMPONENT_DEFINITION_DISABLED: string,
 *     PAGE_DEFINITION_URI: string, PAGE_DEFINITION_LAYOUT: string, PAGE_DEFINITION_IS_ANONYMOUS:
 *     string, UNIT_DEFINITION_PUSHED_URIS: string, HELPER_PARAM_PARAMS: string,
 *     HELPER_PARAM_OVERRIDE: string, HELPER_PARAM_COMBINE: string, HELPER_PARAM_SCOPE: string,
 *     COMBINED_RESOURCES_SEPARATOR: string, COMBINED_RESOURCES_URL_TAIL: string,
 *     CACHE_KEY_UUF_CONF: string, CACHE_KEY_UUF_CONF_FILE_LMD: string, CACHE_KEY_APP_CONF: string,
 *     CACHE_KEY_APP_CONF_FILE_LMD: string, CACHE_KEY_LOOKUP_TABLE: string, CACHE_KEY_USER: string,
 *     CACHE_KEY_SSO_SESSIONS: string, CACHE_KEY_HANDLEBARS_ROOT: string, URL_PARAM_REFERER:
 *     string}}
 */
var constants = {
    // Paths - Directories
    DIRECTORY_APP: "/app",
    DIRECTORY_APP_LAYOUTS: "/app/layouts",
    DIRECTORY_APP_PAGES: "/app/pages",
    DIRECTORY_APP_UNITS: "/app/units",
    DIRECTORY_APP_UNIT_PUBLIC: "public",
    DIRECTORY_CACHE: "/cache",
    DIRECTORY_CONF: "/conf",
    DIRECTORY_LIB: "/lib",
    DIRECTORY_MODULES: "/modules",
    // Paths - Files
    FILE_APP_CONF: "/app/conf/app-conf.json",
    FILE_UUF_CONF: "/app/conf/uuf-conf.json",
    // Paths - Module
    MODULE_AUTH: "/lib/modules/auth/auth.js",
    MODULE_HANDLEBARS: "/lib/modules/handlebars/handlebars.js",
    MODULE_LESS: "/lib/modules/less/less.js",
    // Configurations - App
    APP_CONF_APP_NAME: "appName",
    APP_CONF_CACHE_ENABLED: "cachingEnabled",
    APP_CONF_DEBUGGING_ENABLED: "debuggingEnabled",
    APP_CONF_PERMISSION_ROOT: "permissionRoot",
    APP_CONF_ADMIN_SERVICES_URL: "adminServicesUrl",
    APP_CONF_LOGIN_PAGE: "loginPage",
    APP_CONF_ERROR_PAGES: "errorPages",
    // Configurations - App - Auth module
    APP_CONF_AUTH_MODULE: "authModule",
    APP_CONF_AUTH_MODULE_ENABLED: "enabled",
    APP_CONF_AUTH_MODULE_TRANSPORT: "transport",
    APP_CONF_AUTH_MODULE_LOGIN: "login",
    APP_CONF_AUTH_MODULE_LOGIN_ON_SUCCESS: "onSuccess",
    APP_CONF_AUTH_MODULE_LOGIN_ON_SUCCESS_SCRIPT: "script",
    APP_CONF_AUTH_MODULE_LOGIN_ON_SUCCESS_PAGE: "page",
    APP_CONF_AUTH_MODULE_LOGIN_ON_FAIL: "onFail",
    APP_CONF_AUTH_MODULE_LOGIN_ON_FAIL_SCRIPT: "script",
    APP_CONF_AUTH_MODULE_LOGIN_ON_FAIL_PAGE: "page",
    APP_CONF_AUTH_MODULE_LOGOUT: "logout",
    APP_CONF_AUTH_MODULE_LOGOUT_ON_SUCCESS: "onSuccess",
    APP_CONF_AUTH_MODULE_LOGOUT_ON_SUCCESS_SCRIPT: "script",
    APP_CONF_AUTH_MODULE_LOGOUT_ON_SUCCESS_PAGE: "page",
    APP_CONF_AUTH_MODULE_LOGOUT_ON_FAIL: "onFail",
    APP_CONF_AUTH_MODULE_LOGOUT_ON_FAIL_SCRIPT: "script",
    APP_CONF_AUTH_MODULE_LOGOUT_ON_FAIL_PAGE: "page",
    APP_CONF_AUTH_MODULE_SSO: "sso",
    APP_CONF_AUTH_MODULE_SSO_ENABLED: "enabled",
    APP_CONF_AUTH_MODULE_SSO_ISSUER: "issuer",
    APP_CONF_AUTH_MODULE_SSO_RESPONSE_SIGNING_ENABLED: "responseSigningEnabled",
    APP_CONF_AUTH_MODULE_SSO_KEY_STORE_NAME: "keyStoreName",
    APP_CONF_AUTH_MODULE_SSO_KEY_STORE_PASSWORD: "keyStorePassword",
    APP_CONF_AUTH_MODULE_SSO_IDENTITY_PROVIDER_ALIAS: "identityProviderAlias",
    APP_CONF_AUTH_MODULE_SSO_IDENTITY_PROVIDER_URL: "identityProviderUrl",
    APP_CONF_AUTH_MODULE_SSO_INTERMEDIATE_PAGE: "intermediatePage",
    // Configurations - UUF
    UUF_CONF_DISPLAY_NAME: "displayName",
    UUF_CONF_LOG_LEVEL: "logLevel",
    UUF_CONF_ERROR_PAGES: "errorPages",
    UUF_CONF_SECURITY_CONSTRAINTS: "securityConstraints",
    // UI Component - JS functions
    UI_COMPONENT_JS_FUNCTION_ON_REQUEST: "onRequest",
    // UI Component - Definition
    UI_COMPONENT_DEFINITION_VERSION: "version",
    UI_COMPONENT_DEFINITION_INDEX: "index",
    UI_COMPONENT_DEFINITION_EXTENDS: "extends",
    UI_COMPONENT_DEFINITION_PERMISSIONS: "permissions",
    UI_COMPONENT_DEFINITION_DISABLED: "disabled",
    UI_COMPONENT_DEFINITION_IS_ANONYMOUS: "isAnonymous",
    // Page - Definition
    PAGE_DEFINITION_URI: "uri",
    PAGE_DEFINITION_LAYOUT: "layout",
    // Unit - Definition
    UNIT_DEFINITION_PUSHED_URIS: "pushedUris",
    // Handlebars helper parameters
    HELPER_PARAM_PARAMS: "_params",
    HELPER_PARAM_OVERRIDE: "override",
    HELPER_PARAM_COMBINE: "combine",
    HELPER_PARAM_SCOPE: "scope",
    // Combined resources URLs
    COMBINED_RESOURCES_SEPARATOR: ",",
    COMBINED_RESOURCES_URL_TAIL: "_/combined.",
    // Cache keys
    CACHE_KEY_UUF_CONF: "_UUF_UUF_CONF",
    CACHE_KEY_UUF_CONF_FILE_LMD: "_UUF_UUF_CONF_FILE_LMD",
    CACHE_KEY_APP_CONF: "_UUF_APP_CONF",
    CACHE_KEY_APP_CONF_FILE_LMD: "_UUF_APP_CONF_FILE_LMD",
    CACHE_KEY_LOOKUP_TABLE: "_UUF_LOOKUP_TABLE",
    CACHE_KEY_USER: "_UUF_USER",
    CACHE_KEY_SSO_SESSIONS: "_UUF_SSO_SESSIONS",
    CACHE_KEY_HANDLEBARS_ROOT: "_UUF_HANDLEBARS_ROOT",
    // URL Query Params
    URL_PARAM_REFERER: "referer"
};
